import os

class QuizzFile:

    def __init__(self):
        self.directory = "QuizzFolder"
        self.question_filename = "./" + self.directory + "/Questions.txt"
        self.answer_filename = "./" + self.directory + "/Answer.txt"
        self.solution_filename = "./" + self.directory + "/Solutions.txt"

    def create_folder(self):
        if not os.path.exists(self.directory):
            os.makedirs(self.directory)

    def get_total_number_of_question(self):
        number = 0
        with open(self.question_filename, encoding='utf-8') as file:
            lines = file.readlines()
            for line in lines:
                number += 1
        return number

    def create_question_file(self):
        with open(self.question_filename, 'w', encoding='utf-8') as file:
            file.write("Quel célèbre dictateur dirigea l’URSS du milieu des années 1920 à 1953 ?\n"
                       "Dans quel pays peut-on trouver la Catalogne, l’Andalousie et la Castille ?\n"
                       "Qui a dit : « Le sort en est jeté » (Alea jacta est) ?\n"
                       "Quel cinéaste a réalisé « Parle avec elle » et « Volver » ?\n"
                       "À qui doit-on la chanson « I Shot the Sheriff » ?\n"
                       "Quel pays a remporté la coupe du monde de football en 2014 ?\n"
                       "Dans quelle ville italienne l’action de la pièce de Shakespeare « Roméo et Juliette » se situe-t-elle ?\n"
                       "Par quel mot désigne-t-on une belle-mère cruelle ?\n"
                       "Qui était le dieu de la guerre dans la mythologie grecque ?\n"
                       "Parmi les animaux suivants, lequel peut se déplacer le plus rapidement ?\n"
                       "Quel est l’impératif du verbe feindre à la première personne du pluriel ?\n"
                       "Quel roi de France proclama l’Édit de Nantes ?\n"
                       "À quel écrivain attribue-t-on la rédaction de l’Illiade et l’Odyssée ?\n"
                       "Qui s’est déclaré « premier flic de France » ?\n"
                       "Quel acteur américain incarne le héros du film de Christopher Nolan de 2014 « Interstellar » ?\n"
                       "Quel est le plus long fleuve de France selon la partie coulant sur le territoire ?\n"
                       "Le drapeau russe est blanc, bleu et…?\n"
                       "Quel journal a été attaqué par des terroristes islamistes en janvier 2015 ?\n"
                       "Quel animal andin de la famille des camélidés est élevé pour sa laine ?\n"
                       "À quel compositeur doit-on les bandes-son de films comme « Il était une fois en Amérique », « Pour une poignée de dollars », ou le « Le clan des Siciliens »?\n"
                       "Quelle est la date de la signature de l’armistice de la Première Guerre mondiale ?\n"
                       "Parmi les pays suivants, lequel n’est pas membre de l’Union européenne ?\n"
                       "Dans quelle ville le Colisée (l’amphithéâtre Flavien) se trouve-t-il ?\n"
                       "Dans quel film Dark Vador déclare-t-il à Luke Skywalker : Je suis ton père ?\n"
                       "Quel est l’album le plus vendu de l’histoire ?\n"
                       "À quel écrivain doit-on le personnage de Boule de Suif ?\n"
                       "Quel est l’accent du deuxième e sur le mot FENETRE ?\n"
                       "Combien de jours une année bissextile compte-t-elle ?\n"
                       "Quel animal est « pan-pan » dans Bambi ?\n"
                       "Quel célèbre écrivain débute son plaidoyer en faveur du capitaine Dreyfus par « J’accuse… » ?\n"
                       "En quelle année Charlemagne se fait-il sacrer empereur ?\n"
                       "À quel célèbre écrivain et philosophe doit-on le « Contrat social » et « La nouvelle Héloïse » ?\n"
                       "Quelle célèbre actrice peut-on admirer dans le film de 1942 « Casablanca » ?\n"
                       "Qui aurait dit « Malheur aux vaincus » (Vae victis) après avoir mis Rome à sac ?\n"
                       "Avec la laine de quel animal fait-on du cachemire ?\n"
                       "Parmi les villes suivantes, laquelle est à la fois en Asie et en Europe ?\n"
                       "À la tête de quel pays Hassan Rohani a-t-il été élu en 2013 ?\n"
                       "Quel pays a pour devise « Je maintiendrai » ?\n"
                       "Quel est l’album le plus vendu des Pink Floyd ?\n"
                       "On écrit des…\n"
                       "Qui est le créateur de du tableau « Le radeau de la Méduse » ?\n"
                       "Avec qui David Bowie chantait-il « Dancing in the street » en 1985 ?\n"
                       "Combien d’états fédérés l’Inde compte-t-elle en 2019 ?\n"
                       "Que signifie « messeoir » ?\n"
                       "Quel écrivain voulait « être Chateaubriand ou rien » ?\n"
                       "Pour quelle raison le film de Wim Wenders « Paris, Texas » est-il ainsi nommé ?\n"
                       "Le BJP, auquel appartient le premier ministre indien Narendra Modi, est-il un parti …\n"
                       "On dit qu’une perruche …\n"
                       "Quel diplomate et entrepreneur français est à l’origine de la création du canal de Suez ?\n"
                       "Qui a dit « ce qui se conçoit bien s’énonce clairement, et les mots pour le dire arrivent aisément » ?")

    def create_answer_file(self):
        with open(self.answer_filename, 'w', encoding='utf-8') as file:
            file.write("Trotski//Lénine//Staline//Molotov\n"
                       "La France//Le Portugal//L'Italie//L'Espagne\n"
                       "Vercingétorix//César//Attila//Auguste\n"
                       "Pedro Almodovar//Pablo Trapero//Guillermo del Toro//Woody Allen\n"
                       "UB40//Jim Morrison//Eric Clapton//Bob Marley\n"
                       "L'Allemagne//L'Italie//Le Brésil//L'Argentine\n"
                       "Venise//Vérone//Milan//Rome\n"
                       "Une marâtre//Une godiche//Une chenapan//Une jocrisse\n"
                       "Apollon//Hermès//Arès//Hadès\n"
                       "Le léopard//Le mgbobe//Le chevreuil//Le springbok\n"
                       "Feignons !//Feins !//Feignez !//Feindez !\n"
                       "Louis XIV//François Ier//Henri IV//Louis XIII\n"
                       "Virgile//Homère//Euripide//Sophocle\n"
                       "Léon Blum//Charles de Gaulle//Aristide Briand//Georges Clemenceau\n"
                       "Léonardo DiCaprio//Brad Pitt//Matthew MacConaughey//Tom Cruise\n"
                       "Le Rhône//La Loire//Le Rhin//La Seine\n"
                       "Rouge//Jaune//Vert//Noir\n"
                       "Libération//Le Monde//Le Figaro//Charlie Hebdo\n"
                       "Le lama//Le yak//Le chameau//Le buffle\n"
                       "John Barry//Vladimir Cosma//Hans Zimmer//Ennio Morricone\n"
                       "11 novembre 1918//11 novembre 1919//8 mai 1918//8 mai 1919\n"
                       "La Suède//La Norvège//Le Danemark//La Finlande\n"
                       "Nîmes//Venise//Barcelone//Rome\n"
                       "Star Trek//2001 L'Odyssée de l'espace//Soleil vert//Star Wars\n"
                       "Their Greatest Hits des Eagles//Back in Black des AC/DC//Come on Over de Shania Twains//Thriller de Michael Jackson\n"
                       "Maupassant//Voltaire//Balzac//Stendhal\n"
                       "L'accent grave//L'accent aigu//L'accent circonflexe//Aucun accent\n"
                       "365//366//364//363\n"
                       "Un chien//Un cerf//Un oiseau//Un lapin\n"
                       "Marcel Proust//Émile Zola//Victor Hugo//Alphonse de Lamartine\n"
                       "756 ap. J.-C.//800 ap. J.-C.//787 ap. J.-C.//843 ap. J.-C.\n"
                       "D'Alembert//Mirabeau//Rousseau//Chateaubriand\n"
                       "Ingrid Bergman//Greta Garbo//Claudia Cardinale//Lauren Bacall\n"
                       "Hannibal Barca//Jules César//Vercingétorix//Brennos\n"
                       "Du mouton//Du vison//Du lapin//De la chèvre\n"
                       "Alexandrie//Rhodes//Moscou//Istanbul\n"
                       "Égypte//Iran//Jordanie//Irak\n"
                       "La Suisse//Les Pays-Bas//La Belgique//L'Angleterre\n"
                       "The Dark Side of the Moon//The Wall//The Final Cut//Wish You Were Here\n"
                       "passe-partout//passes-partout//passe-partouts//passes-partouts\n"
                       "Delacroix//Courbet//David//Géricault\n"
                       "Bruce Spingsteen//Michael Jackson//Paul McCartney//Mick Jagger\n"
                       "28//30//27//29\n"
                       "Que la mort accompagne.//Ne pas être convenable.//D'une couleur qui tire sur le blond.//Réservé aux seuls initiés.\n"
                       "Musset//Rimbaud//Zola//Hugo\n"
                       "Parce que le héros chercherait à retrouver une ville perdue nommé Paris, au Texas.//Parce que le héros du film aurait été conçu à Paris, au Texas.//Parce que le personnage principal fait un voyage de Paris au Texas.\n"
                       "de droite nationaliste ?//de gauche anticapitaliste ?//de centre-droit ?//de centre-gauche ?\n"
                       "jabote.//feule.//zinzinule.//pupule.\n"
                       "Philippe Bunau-Varilla//Hubert Lyautey//Ferdinand de Lesseps//Gustave Eiffel\n"
                       "Chamfort//Marivaux//Molière//Boileau")

    def create_solution_file(self):
        with open(self.solution_filename, 'w', encoding='utf-8') as file:
            file.write("Staline\n"
                       "L'Espagne\n"
                       "César\n"
                       "Pedro Almodovar\n"
                       "Bob Marley\n"
                       "L'Allemagne\n"
                       "Vérone\n"
                       "Une marâtre\n"
                       "Arès\n"
                       "Le springbok\n"
                       "Feignons !\n"
                       "Henri IV\n"
                       "Homère\n"
                       "Georges Clemenceau\n"
                       "Matthew MacConaughey\n"
                       "La Loire\n"
                       "Rouge\n"
                       "Charlie Hebdo\n"
                       "Le lama\n"
                       "Ennio Morricone\n"
                       "11 novembre 1918\n"
                       "La Norvège\n"
                       "Rome\n"
                       "Star Wars\n"
                       "Thriller de Michael Jackson\n"
                       "Maupassant\n"
                       "L'accent circonflexe\n"
                       "366\n"
                       "Un lapin\n"
                       "Émile Zola\n"
                       "800 ap. J.-C.\n"
                       "Rousseau\n"
                       "Ingrid Bergman\n"
                       "Brennos\n"
                       "De la chèvre\n"
                       "Istanbul\n"
                       "Iran\n"
                       "Les Pays-Bas\n"
                       "The Dark Side of the Moon\n"
                       "passe-partout\n"
                       "Géricault\n"
                       "Mick Jagger\n"
                       "29\n"
                       "Ne pas être convenable.\n"
                       "Hugo\n"
                       "Parce que le héros du film aurait été conçu à Paris, au Texas.\n"
                       "de droite nationaliste ?\n"
                       "jabote.\n"
                       "Ferdinand de Lesseps\n"
                       "Boileau")

    def create_quizz_files(self):
        self.create_folder()
        self.create_question_file()
        self.create_solution_file()
        self.create_answer_file()